spring:
  application:
    name: microservice-sidecar
server:
  port: 8070
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
sidecar:
  port: 8060  #异构应用端口 必须在同一个host 如果不是同一个 需要配置 eureka.instance.hostname
  health-uri: http://localhost:8060/health.json