server:
  port: 7900
spring:
  datasource:
        url: jdbc:mysql://localhost:3306/idea?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: anhf
        password: anhf
        driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
  application:
    name: microservice-provider-user
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}




