server:
  port: 7900
spring:
  datasource:
        url: jdbc:mysql://localhost:3306/idea?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: anhf
        password: anhf
        driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update




